### ISSUE TITLE
Changing name of resources creates new ones

### ISSUE THREAD

**Issue by jagregory** [akshaykarle/terraform-provider-mongodbatlas#13]
Changing the name of a Project and a Cluster (the two I've tried) results in new resources being created. This doesn't seem right?

Thanks for the project btw, this is exactly what I needed. :)

**Comment by akshaykarle** [comment]
Hey @jagregory, thanks for the feedback :)

Unfortunately the MongoDB Atlas API does not support any update or delete to the project although you may be able to do it from the UI. If you notice the [project API docs](https://docs.atlas.mongodb.com/reference/api/projects/), it only allows reading and creating a project.

The cluster name is something the [API uses to identify the cluster](https://docs.atlas.mongodb.com/reference/api/clusters-modify-one/), so updating the name of the cluster would result in creating a new cluster.

**Comment by akshaykarle** [comment]
I will close this issue for now, as I'm unsure what I can do about this.

**Comment by jagregory** [comment]
Thanks @akshaykarle for the reply. My apologies, I didn’t realise how limited the Atlas API is.
