### ISSUE TITLE
Terraform Data Sources support

### ISSUE THREAD

**Issue by ctaverne** [akshaykarle/terraform-provider-mongodbatlas#15]
Hi,

First, thanks for sharing this project.

I'd like to know if it is possible to retrieve state meta data from a remote backend with current datasource usage ? or only create resource ?

example:

```
data "terraform_remote_state" "vpc" {
  backend = "atlas"
  config {
    name = "hashicorp/vpc-prod"
  }
}
```

It could be very usefull due to actual limitation with container or project  because we can't drop them with API for now.

thanks

**Comment by akshaykarle** [comment]
Hey @ctaverne, so if I understand correctly, you would like to use data sources for containers and projects since you cannot delete them using the terraform provider or the api?

**Comment by akshaykarle** [comment]
Yes, I understand now. That is a good idea! I will add this to the backlog and will see the effort required to implement it. Thank you for sharing that thought :)

**Comment by ctaverne** [comment]
Hi @akshaykarle 
Thank you to you for sharing this project !

regards,
