### ISSUE TITLE
Terraform destroy didn't destroy my resource

### ISSUE THREAD

**Issue by LieAlbertTriAdrian** [akshaykarle/terraform-provider-mongodbatlas#18]
Hi there,

I tried to destroy my resource because I didn't use it again, but the resource is not deleted.

```
resource "mongodbatlas_project" "test-project" {
    org_id = "xxxx"
    name = "terraform-test-project"
}
```
I think it's because the destroy logic is just `return nil`. Is this intentional? 
https://github.com/akshaykarle/terraform-provider-mongodbatlas/blob/master/mongodbatlas/project.go#L75

**Comment by akshaykarle** [comment]
Hey @LieAlbertTriAdrian, this is a limitation of the Mongo Atlas API, as it doesn't allow deleting of projects from the API as you can see it in their docs [here](https://docs.atlas.mongodb.com/reference/api/projects/).

I'm closing this issue as there is not much I can do until they implement DELETE of projects in their API.
