### ISSUE TITLE
Publish to terraform modules

### ISSUE THREAD

**Issue by shawnmclean** [akshaykarle/terraform-provider-mongodbatlas#19]
Is it possible to publish this plugin to the terraform modules registry?

https://registry.terraform.io/

**Comment by shawnmclean** [comment]
Awesome!

There is a warning on the website now: `This module version (0.4.5) has no root configuration. A module with no root configuration cannot be used directly.`

**Comment by akshaykarle** [comment]
Yes, I noticed. Will try to fix that over the weekend. Thank you for pointing that out :-)

**Comment by NRaf** [comment]
Has this been resolved?

When I run `terraform get` I get the following error:

> Error downloading modules: Error loading modules: module mongodbatlas: No Terraform configuration files found in directory: .terraform/modules/a7ef87aec1d3b6f8c48b8be5386d48f6/akshaykarle-terraform-provider-mongodbatlas-d209238
