### ISSUE TITLE
Terraform Provider Development Program

### ISSUE THREAD

**Issue by cgriggs01** [akshaykarle/terraform-provider-mongodbatlas#27]
Hi All! 👋 

I have opened this PR for the purpose of preparing the MongoDB Atlas Terraform provider for review and release into the official Terraform ecosystem.  The following list are items that should be addressed before moving on tot the technical review and release portion of the program. 

- [x] File naming conventions: the resource files in the provider must follow the strict naming convention with the prefix `resource_mongodbatlas_` follow by the resource name ie `container.go` This is the same for datasources, which are already correct. 

- [ ] Each resource and data source must have a corresponding test file with the postfix `_test.go`. Our goal for all provider is to have at lease 50%  code coverage across the acceptance test. To learn more about Terraform provider acceptance testing, we recently published some new [testing documentation](https://www.terraform.io/docs/extend/testing/index.html) on the subject. 

- [x] The project resource's `delete` method should be completed or removed. 

- [x] The container resource's methods `delete` and `update` should be implemented

- [x] The ip_whitelist resource method `update` should be implemented or removed

- [x] The vpc_peering_connection resource's method `update` should be implemented or removed

- [x] There are two additional bash scripts that are used during the release process. [changelog-links.sh](https://github.com/terraform-providers/terraform-provider-aws/blob/master/scripts/changelog-links.sh) and [gogetcookie.sh](https://github.com/terraform-providers/terraform-provider-aws/blob/master/scripts/gogetcookie.sh). Can you please add these to the scripts/ directory. 

- [x] You will need to update you .travis.yaml file to align with the terraform provider [std travis config](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.travis.yml)

- [x] There are two targets `website` and `website-test` that must be added to the GNUmakefile. You can find the necessary change in this [PR](https://github.com/terraform-providers/terraform-provider-scaffolding/commit/11562442f6bf9e7ac71f1aa1c15823a1b26f2a8d).

Once these are complete we can start testing the provider against a MongoDB Atlas env, after the tests pass we will start the technical review with one of our Terraform Engineers. 

Please let me know if you have any questions.

Best,
Chris

**Comment by akshaykarle** [comment]
Hey @cgriggs01 thanks for taking the time to put this list together. I've been busy the last few weeks but I do have some time finally so I will start looking at these soon. Will keep you update as I work through them :)

**Comment by akshaykarle** [comment]
@cgriggs01 when I tried to remove the unimplemented `delete` methods on `project` and `container`, the provider test gives me the following error:
```
--- FAIL: TestProvider (0.00s)
	provider_test.go:11: err: 2 error(s) occurred:

		* resource mongodbatlas_project: Delete must be implemented
		* resource mongodbatlas_container: Delete must be implemented
FAIL
```
The [MongoDB Atlas API](https://docs.atlas.mongodb.com/reference/api-resources/) doesn't provide methods to delete a Container or a Project so I'm unable to implement these methods. How should I proceed? Just leave those methods unimplemented for now?

**Comment by dpiddockcmp** [comment]
Hi @akshaykarle. I just deleted an empty Project using the API documented here: https://docs.atlas.mongodb.com/reference/api/project-delete-one/

**Comment by akshaykarle** [comment]
Yup @dpiddockcmp, planning to add that soon to the provider :)

**Comment by cgriggs01** [comment]
Hey ya'll,

I am having some issue running the acceptance tests against my MongoDB Atlas account, nd consistantly getting this error on most of the tests:
```
=== RUN   TestAccMongodbatlasDataSource_Project
--- FAIL: TestAccMongodbatlasDataSource_Project (1.15s)
    <autogenerated>:1: Step 0 error: Error refreshing: 1 error(s) occurred:

        * data.mongodbatlas_project.test: 1 error(s) occurred:

        * data.mongodbatlas_project.test: data.mongodbatlas_project.test: Error reading MongoDB Project with name test: MongoDB Atlas: 401 The current user is not in the group, or the group does not exist.
```
Any thoughts on how to fix this?

**Comment by akshaykarle** [comment]
hey @cgriggs01 i invited you to the test project just now. Can you accept my invitation and try running the tests again please?

**Comment by cgriggs01** [comment]
Ok, I accepted the invite. 

But am still getting those errors. I beleive its because the acceptance tests are calling `projectName := "test"` while the name of the project on the test account is `Terraform Test Project 0'. Should those be the same project name or am I totally wrong? 

Let me know. Thanks!

**Comment by holms** [comment]
*Silently cheering for getting this provider to official registry*

**Comment by cgriggs01** [comment]
Hey @akshaykarle 

 - [ ] When running the acceptance tests. We’re still running into a few failed tests. The first two, there seems to been an error when destroying the test resource cluster. The third failed test looks to be an error with provisioning in US_EAST_1, is there another region that this should be tested in?

```
=== RUN   TestAccMongodbatlasCluster_basic
--- FAIL: TestAccMongodbatlasCluster_basic (1187.13s)
    testing.go:599: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: Check failed: Cluster "5c3792fc79358e2124a76e47" still exists

        State: <no state>
=== RUN   TestMongodbatlasCluster_importBasic
--- FAIL: TestMongodbatlasCluster_importBasic (511.79s)
    testing.go:599: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.

        Error: Check failed: Cluster "5c37979fc56c989c8c692778" still exists

        State: <no state>
=== RUN   TestAccMongodbatlasContainer_basic
--- FAIL: TestAccMongodbatlasContainer_basic (1.57s)
    testing.go:538: Step 0 error: Error applying: 1 error(s) occurred:

        * mongodbatlas_container.test: 1 error(s) occurred:

        * mongodbatlas_container.test: Error creating MongoDB Container: MongoDB Atlas: 409 Cannot modify in use containers. Resources already exist in US_EAST_1. Creating resources in US_EAST_1 is not supported..
```

- [ ] The datasource for container and resources for alert configuration and VPC peering connection do not have corresponding tests. Do you plan to add these test files?

Although the items above should be address before provider official release, I’m going to move this provider into the queue to be review by one of our Terraform ecosystem engineers. You’ll be the 3rd integration in the queue so it will be a few weeks before an engineer is available to review. 

Let me know if you have any questions about those.

**Comment by akshaykarle** [comment]
Closing this one since we have https://github.com/akshaykarle/terraform-provider-mongodbatlas/issues/68 which covers what is remaining on this issue
