### ISSUE TITLE
The deletion of projects is not handled properly 

### ISSUE THREAD

**Issue by jjuarez** [akshaykarle/terraform-provider-mongodbatlas#30]
We're handling this resource as part of the items related with MongoDB Atlas and it's created well, but during the destroy phase it doesn't appear as part of the resources to handle, so we've some issues to recreate the clusters inside the same project. We're using Terraform 0.11.7 + Terragrunt 0.16.4, and the version 0.6.2 of the provider

**Comment by akshaykarle** [comment]
Hello @jjuarez, projects can't be destroyed as the MongoDB Atlas API doesn't expose an API endpoint to delete a project. Have a look at https://github.com/akshaykarle/terraform-provider-mongodbatlas/issues/18 for more info. Closing this now as there is not much I can do about it.

**Comment by jjuarez** [comment]
Ok, I see, sorry for the inconvenience
