### ISSUE TITLE
Error: 400 An invalid enumeration value M10 was specified

### ISSUE THREAD

**Issue by feraudet** [akshaykarle/terraform-provider-mongodbatlas#49]
Hello,

When I try to create a cluster bigger than M2 I get this kind of message :
"400 An invalid enumeration value M10 was specified."

Plateform : AWS
Region: eu-west-1

Have you an idea ?

**Comment by v00d00** [comment]
Maybe post your config block?

**Comment by feraudet** [comment]
Just found why : 
- provider_name was TENANT (mandatory for M0/1/2)
- backing_provider was AWS
But for non shared cluster : 
- provider_name need to be set to AWS (or other cloud provider)
- backing_provider mustn't be set

**Comment by ervinb** [comment]
We got the same issue recently, when we were trying to create an M20 cluster in `europe-west1` (Atlas region: `EUROPE_WEST_1`).

The same config worked for an M10 setup in `europe-west3` (Atlas region: `EUROPE_WEST_3`). The region values are from: https://docs.atlas.mongodb.com/reference/google-gcp/


```
resource "mongodbatlas_cluster" "default" {
  name                  = "${var.name}"
  group                 = "${var.project_id}"
  mongodb_major_version = "${var.mongodb_major_version}"
  provider_name         = "${var.provider_name}"
  region                = "${var.region}"
  size                  = "${var.tier}"
  backup                = true
}
```

It failed no matter which instance type we tried on `EUROPE_WEST_1`.

A colleague of mine got the genius idea to inspect the HTML form when attempting to create the Atlas cluster manually, and found that the region code is *of course* `WESTERN_EUROPE` for `europe-west1` and **not** `EUROPE_WEST_1` like in the docs.

**Comment by hpio** [comment]
For anyone having the same issue, here https://docs.atlas.mongodb.com/reference/google-gcp/#google-gcp-availability-zones you can find ATLAS_REGION names corresponding to GCP regions

**Comment by ghost** [comment]
the free cluster and if there is no support for that size in that region it throws enumeration error, though old post just responding as i just saw simillar issue

**Comment by dharmik-st** [comment]
The enumeration error occurs while applying the free tier instances of MongoDB.
e.g: **M0, M2, M5** are not supported while applying using Terraform

ERROR: "No payment information was found for group"
Resolution: If you're trying to create it using M10, M20, etc You need to configure your payment options in MongoDB (Credit Card or any other payment method)

**Comment by EbrahemM7** [comment]
@dharmik-st  , in case i`m paying to gcp using a third-party method , how can I use mongodb Atlas without adding a credit card ?
