### ISSUE TITLE
Add attribute for short SRV connection string

### ISSUE THREAD

**Issue by mkozjak** [akshaykarle/terraform-provider-mongodbatlas#67]
On cloud.mongodb.com there's a way to also get a short SRV connection string, with protocol `mongodb+srv`. Would it be possible to expose it here?

```
mongodb+srv://user:password@data.gcp.mongodb.net/test?retryWrites=true
```

**Comment by danielsiwiec** [comment]
@akshaykarle this issue can be closed, once the new release is published

**Comment by akshaykarle** [comment]
Thanks @danielsiwiec Closing this now that the new release is published
