### ISSUE TITLE
Configure provider from environment variables

### ISSUE THREAD

**Issue by chris-scentregroup** [akshaykarle/terraform-provider-mongodbatlas#70]
Would it be ok to do a PR to optionally have the provider use environment variables for the configuration, something like `MONGODB_ATLAS_PUBLIC_API_KEY` and `MONGODB_ATLAS_PUBLIC_API_KEY`?

**Comment by dpiddockcmp** [comment]
Hi Chris.

This is already supported! 😄 

`MONGODB_ATLAS_USERNAME` and `MONGODB_ATLAS_API_KEY`. Documentation here: https://github.com/akshaykarle/terraform-provider-mongodbatlas/blob/master/website/docs/index.html.markdown#environment-variables

**Comment by chris-scentregroup** [comment]
Oh that is great, but its missing from the main readme? I think thats likely the problem..

**Comment by akshaykarle** [comment]
Hey @chris-scentregroup closing this as it works as expected. Thank you for the doc suggestion, PRs would be welcome :)
