### ISSUE TITLE
Support for VPC Peering with GCP

### ISSUE THREAD

**Issue by BrendanThompson** [akshaykarle/terraform-provider-mongodbatlas#74]
@akshaykarle there is support for GCP VPC within MongoDB Atlas, what would be involved in getting that support into the TF provider here?

**Comment by akshaykarle** [comment]
Hey @BrendanThompson you will have to first add support for GCP into the [go-mongodbatlas](https://github.com/akshaykarle/go-mongodbatlas/blob/master/mongodbatlas/containers.go) repo and then update the container resource to handle those new api fields.

It will also be helpful if you could add an acceptance test to the [resource_mongodbatlas_container_test.go](https://github.com/akshaykarle/terraform-provider-mongodbatlas/blob/master/mongodbatlas/resource_mongodbatlas_container_test.go)

**Comment by BrendanThompson** [comment]
Hey @akshaykarle, yeah assign it to me. So in order to support this we need to update the following, in this repo:

* `resource_mongodbatlas_vpc_peering_connection`
* `resource_mongodbatlas_container`
* `data_source_mongodbatlas_container`

My question here is, would it make more sense to have separate `resource` types for GCP and AWS, perhaps as per the following:

* `resource_mongodbatlas_gcp_vpc_peering_connection`
* `resource_mongodbatlas_aws_vpc_peering_connection`

As we are changing up the required fields ( _e.g. – `networkName`, `gcpProjectId`_, `vpcId` ) it makes sense to me to have them as separate `resource` files, however, I am not experienced in creating providers; in fact, this is my first time modifying a provider.

**Comment by BrendanThompson** [comment]
Ignore what is above, I have worked it all out, I think.
