### ISSUE TITLE
Support setting Datadog API Key

### ISSUE THREAD

**Issue by simonharrer** [akshaykarle/terraform-provider-mongodbatlas#76]
Atlas now supports sending metrics to datadog. It's not part of the alert configuration, but named 'integration' where one can set the datadog API key for each project. Support for setting this datadog API key through this terraform plugin would be marvellous.

I can offer assistance in testing this feature.

![Screenshot 2019-03-14 at 11 48 06](https://user-images.githubusercontent.com/375693/54351103-0e6e9680-464f-11e9-921e-67069a69e712.png)

**Comment by akshaykarle** [comment]
Hey @simonharrer thanks for the feature request, but at this time I couldn't find anyway to integrate with the datadog API using the [mongo atlas API](https://docs.atlas.mongodb.com/api/) which makes configuring this integration using terraform hard. I will forward your request to the mongo team to see if they can provide an API endpoint for this. If you have noticed any way of doing this let me know. I will close this for now until I hear back from Mongo.
