### ISSUE TITLE
Add support to query container id

### ISSUE THREAD

**Issue by joonhwa** [akshaykarle/terraform-provider-mongodbatlas#92]
Is it possible to add a data source to query for container id? This ID is required when creating peering connection and i would like to query for it rather than storing it as a config in my code.

Thanks.

**Comment by akshaykarle** [comment]
Hey @joonhwa there is already a [data source for containers](https://github.com/akshaykarle/terraform-provider-mongodbatlas/blob/master/website/docs/d/container.html.markdown) but you do need to pass it a group and identifier (ID) as the MongoDB Atlas API only supports querying containers by ID. If you are creating a peering connection you should be able to create the data source and pass it to your VPC peering connection
